-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(TOTAL_SALES * PRICE) TOTAL_SALES
FROM (
    SELECT BOOK_ID, SUM(SALES) TOTAL_SALES
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01%'
    GROUP BY BOOK_ID
) TBL
LEFT JOIN BOOK B
ON TBL.BOOK_ID = B.BOOK_ID
LEFT JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY 1, 3
ORDER BY 1, 3 DESC;