-- 코드를 입력하세요
SELECT PC.PRODUCT_CODE, IFNULL(PC.PRICE*SUM(OS.SALES_AMOUNT),0) SALES
FROM PRODUCT PC
LEFT JOIN OFFLINE_SALE OS
ON PC.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY PC.PRODUCT_ID
ORDER BY SALES DESC, PC.PRODUCT_CODE