-- 코드를 입력하세요
-- 1. 자동차 종류가 '세단' 또는 'SUV'인 자동차 중 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고 30일간 대여 금액이 50만원 이상 200만원 미만인 자동차
-- 2. 자동차 ID, 자동차 종류, 대여 금액(FEE) 출력
-- 3. 30일간 대여 금액 내림차순, 자동차 종류 오름차순, 자동차 ID 내림차순

SELECT *
FROM (
    SELECT CRCC.CAR_ID, CRCC.CAR_TYPE, ROUND(CRCC.DAILY_FEE * 30 * (1.0-CRCDP.DISCOUNT_RATE*0.01),0) FEE
    FROM CAR_RENTAL_COMPANY_CAR CRCC
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
    ON CRCC.CAR_ID = CRCRH.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
    ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE
    WHERE CRCDP.DURATION_TYPE = '30일 이상'
    AND CRCC.CAR_TYPE IN ('세단', 'SUV')
    AND CRCC.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY TMP
        WHERE ('2022-11-01' BETWEEN START_DATE and END_DATE) 
               or ('2022-11-30' BETWEEN START_DATE and END_DATE))
) LIST
WHERE FEE BETWEEN 500000 AND 2000000
GROUP BY LIST.CAR_ID
ORDER BY FEE DESC, LIST.CAR_TYPE, LIST.CAR_ID DESC;