-- 코드를 입력하세요
WITH TBL AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO RI
LEFT JOIN TBL T
ON RI.FOOD_TYPE = T.FOOD_TYPE
WHERE RI.FAVORITES = MAX
ORDER BY RI.FOOD_TYPE DESC