-- 코드를 입력하세요

SELECT 
    RI.REST_ID, 
    RI.REST_NAME, 
    RI.FOOD_TYPE, 
    RI.FAVORITES, 
    RI.ADDRESS, 
    (SELECT ROUND(AVG(RR.REVIEW_SCORE),2) FROM REST_REVIEW RR WHERE RR.REST_ID LIKE RI.REST_ID) SCORE
FROM REST_INFO RI
WHERE RI.ADDRESS LIKE '서울%'
AND (SELECT COUNT(RR.REVIEW_SCORE) FROM REST_REVIEW RR WHERE RR.REST_ID LIKE RI.REST_ID) NOT LIKE 0
ORDER BY SCORE DESC, RI.FAVORITES DESC;