-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, GENDER, COUNT(DISTINCT OS.USER_ID) USERS
FROM ONLINE_SALE OS
LEFT JOIN USER_INFO UI
ON OS.USER_ID = UI.USER_ID
GROUP BY 1, 2, 3
HAVING GENDER IS NOT NULL
ORDER BY 1, 2, 3;