-- 코드를 입력하세요
SELECT
    LIST.HISTORY_ID
    ,ROUND((LIST.DAILY_FEE * (1.0-IFNULL(CRCDP.DISCOUNT_RATE*0.01,0)))*LIST.DAYS,0) FEE
FROM(
    SELECT 
        CRCR.HISTORY_ID
        ,CRCC.DAILY_FEE
        ,(DATEDIFF(END_DATE,START_DATE)+1) DAYS
        ,CASE WHEN (DATEDIFF(END_DATE,START_DATE)+1) >= 90 THEN '90일 이상'
            WHEN (DATEDIFF(END_DATE,START_DATE)+1) >= 30 THEN '30일 이상'
            WHEN (DATEDIFF(END_DATE,START_DATE)+1) >= 7 THEN '7일 이상' END DIFF
    FROM CAR_RENTAL_COMPANY_CAR CRCC
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCR
    ON CRCC.CAR_ID = CRCR.CAR_ID
    WHERE CRCC.CAR_TYPE = '트럭'
) LIST
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
ON LIST.DIFF = CRCDP.DURATION_TYPE
AND CRCDP.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;