-- 코드를 입력하세요
WITH RECURSIVE HOURS AS(
    SELECT 0 AS H
    UNION ALL
    SELECT H+1 FROM HOURS WHERE H<23
)
SELECT HR.H HOUR, COUNT(DATETIME) COUNT
FROM HOURS HR
LEFT JOIN ANIMAL_OUTS AO
ON HR.H = HOUR(AO.DATETIME)
GROUP BY 1
ORDER BY 1