-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD UGB
LEFT JOIN USED_GOODS_USER UGU
ON UGB.WRITER_ID = UGU.USER_ID
WHERE STATUS LIKE 'DONE'
GROUP BY 1
HAVING SUM(PRICE) >= 700000
ORDER BY 3