-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE MP
LEFT JOIN REST_REVIEW RR
ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE RR.MEMBER_ID = (SELECT RRR.MEMBER_ID FROM REST_REVIEW RRR GROUP BY RRR.MEMBER_ID ORDER BY COUNT(RRR.MEMBER_ID) DESC LIMIT 1)
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT