-- 코드를 입력하세요
WITH TBL AS(
    SELECT CATEGORY, MAX(PRICE) PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
)
SELECT FP.CATEGORY, FP.PRICE MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT FP
LEFT JOIN TBL T
ON FP.CATEGORY = T.CATEGORY
WHERE FP.CATEGORY IN ('과자','국','김치','식용유')
AND FP.PRICE = T.PRICE
ORDER BY 2 DESC;